src/csfilter.cc
... in order to ease defining filters that apply to multiple checkers
=> csfilter: match checker as regex in MsgFilter

.travis.yml, .travis/README, .travis/copr-build, .travis/copr-build-setup, .travis/copr-custom-script
Builds after pushes go to [1], builds for pull-request to [2].
[1] https://copr.fedorainfracloud.org/coprs/g/codescan/csdiff/
[2] https://copr.fedorainfracloud.org/coprs/g/codescan/csdiff-pull-requests/
=> travis: automatically build csdiff in Fedora Copr

.travis.yml, .travis/copr-build
travis: run copr build only for the master branch
This is needed to avoid building into the @codescan/csdiff copr project
upon push to non-master branch.  Also, pull-requests against non-master
branch would be excluded, but they should be rare.
Drop the -x flag from the Travis build.  That PR webhook isn't a private
information but still..  it is better to not make a honeypot from all
our Travis logs.
=> travis: run copr build only for 'master' branch

.travis.yml
Since my github account is used as upstream, I always need to create a branch before I submit a pull request.  It does not make any sense to trigger the jobs twice for the same git tree.
.travis.yml: run the copr build job as first in the matrix because it usually takes long time to complete.
=> .travis.yml: trigger jobs for the master branch only

.travis/copr-custom-script
This is not needed when the build is triggered manually in Copr.
=> travis: don't require GitHub webhook payload

make-srpm.sh
... on Fedora Rawhide (while preserving compatibility with RHEL-7)
=> make-srpm.sh: fix build failure with updated RPM macros

src/csv-parser.cc, src/csv-parser.hh
There were two instances of the flag by mistake.  Detected by Coverity.
=> csv-parser: fix use of uninitialized member `silent`

.packit.yaml
We should be using the same versioning scheme so that we don't unintentionally break package upgrades.
Blocks: #56
=> CI: make Packit use the same `%{version}.%{release}` as `make-srpm.sh`

src/CMakeLists.txt
Otherwise, e.g. month could be in other language when `LC_TIME` was set to such locale.
Fixes: `Wide character in print at /usr/bin/help2man line 672.`
=> doc: use C locale when generating manual pages

make-srpm.sh
* use `%autosetup` instead of `%setup -q`
* use `%cmake3{,_build,_install}` and `%ctest3` macros
* make links point to the upstream repository
* unify condition format across spec file
* use `%license` instead of `%doc` for `COPYING`
* use `%py_provides` instead of deprecated `%python_provide`
* fix typos
* remove dependency on `boost-python2-devel` for Fedora
=> Modernize spec file

doc/csdiff.h2m, doc/csgrep.h2m
* document csgrep's `--mode=sarif` option
* fix example syntax with empty `replace` key and cs{diff,grep}
* do not print spaces between bold text and punctuation
=> Update man pages

Makefile, make-srpm.sh, tests/cssort/sync-diff.sh
Replace `` `cmd` `` with `$(cmd)`.
=> bash: use modern syntax for command substitution

.github/workflows/differential-shellcheck.yml
Differential ShellCheck is a GitHub action that performs differential ShellCheck scans on files changed via PR and reports results directly in PR.
Since this repository contains some shell scripts I think you might find it useful.
Documentation is available at: [@redhat-plumbers-in-action/differential-shellcheck](https://github.com/redhat-plumbers-in-action/differential-shellcheck#readme). Let me know If you are missing some feature or setting.
/cc @kdudka
=> Add Shell linter - Differential-ShellCheck

.github/workflows/coverity.yml
Similar to: https://github.com/csutils/cswrap/pull/32
=> Run `coverity` workflow only on primary repository

.github/workflows/ci.yml
They are deprecated according to the GitHub Blog [1] and will be removed by
the end of November.
[1] https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/
=> CI: drop Ubuntu 18.04 jobs

src/abstract-parser.cc, src/abstract-parser.hh, src/color.cc, src/color.hh, src/csdiff.cc, src/csfilter.cc, src/csfilter.hh, src/csparser.hh, src/gcc-parser.hh, src/instream.cc, src/instream.hh, src/json-parser.hh
=> Port the project to C++11 - Part 2

src/cstrans-df-run.cc
We can use `std::ifstream` and `std::ofstream` to simplify construction of the stream objects.  And we do not need to close the streams when they are going to be destroyed (and hence automatically closed).
=> cstrans-df-run: simplify the code using C++11 extensions

.packit.yaml
[update_release](https://packit.dev/docs/configuration/#update_release) is a new way how to tell Packit to not update the release string
=> CI: use update_release instead of release_suffix

src/lib/parser-json-simple.cc
... with gcc-13.0.1-0.2.fc38.x86_64:
```
src/lib/parser-json-simple.cc: In member function ‘virtual void SimpleTreeDecoder::readScanProps(TScanProps*, const boost::property_tree::ptree*)’:
src/lib/parser-json-simple.cc:110:22: warning: possibly dangling reference to a temporary [-Wdangling-reference]
110 |     const pt::ptree &scanNode =
|                      ^~~~~~~~
src/lib/parser-json-simple.cc:111:54: note: the temporary was destroyed at the end of the full expression ‘boost::property_tree::basic_ptree<Key, Data, KeyCompare>::get_child_optional(const path_type&) const [with Key = std::__cxx11::basic_string<char>; Data = std::__cxx11::basic_string<char>; KeyCompare = std::less<std::__cxx11::basic_string<char> >; path_type = boost::property_tree::string_path<std::__cxx11::basic_string<c …
```
=> parser-json-simple: eliminate `-Wdangling-reference` false positive

src/lib/filter.cc, tests/csgrep/0110-warning-rate-limit-stdout.txt, tests/csgrep/sync.sh
The code used a string that was already overwritten for the error event.
=> csgrep --warning-rate-limit: fix msg of the note event

src/CMakeLists.txt, src/lib/parser-gcc.cc, tests/csgrep/0112-gcc-parser-ubsan-bt-stdout.txt
UBSAN may only use the base name for the file path in its key event. However, the top of the backtrace, if present, always contains the whole path to this file.
This fixes `csmock` throwing all UBSAN warnings into the suppressed category.
=> parser-gcc: fix incomplete file paths in UBSAN key events

src/lib/parser-json-cov.cc, tests/csgrep/0061-json-parser-cov-v7-lang-stdout.txt
Resolves: https://issues.redhat.com/browse/OSH-289
=> parser-json-cov: treat defects with high impact as important

src/lib/writer-json-sarif.cc, src/lib/writer-json-sarif.hh, tests/csgrep/0090-sarif-writer-illegal-utf8-sequence-stdout.txt, tests/csgrep/0096-sarif-levels-stdout.txt, tests/csgrep/0097-sarif-set-tool-stdout.txt, tests/csgrep/0109-shellcheck-sarif-cwe-stdout.txt
... to ease SARIF import into Defect Dojo
Resolves: https://issues.redhat.com/browse/OSH-355
=> writer-json-sarif: add tool to rule properties

src/CMakeLists.txt
The newest installed version of Python 3 is often not the default version on a Gentoo Linux system, where multiple Python 3 versions can be installed on a single system and /usr/bin/python3 is the one that should be used by default.
Related: https://gitlab.kitware.com/cmake/cmake/-/merge_requests/8287
=> cmake: make FindPython use system Python 3 version

src/cshtml.cc, src/lib/parser-common.cc, src/lib/parser-cov.cc, src/lib/parser-json-sarif.cc, src/lib/parser-xml-valgrind.cc, src/lib/writer-html.cc, src/lib/writer-json-sarif.cc
=> lint: use std::move() where appropriate

src/lib/writer-json-sarif.cc
For a reason I'm too lazy to diagnose, latest releases of Apple Clang now ignore the outermost initializer lists with object initializers which GCC still translates to an array.  Construct the arrays explicitly to avoid this ambiguity.
Resolves: https://github.com/csutils/csdiff/issues/160
=> writer-json-sarif: fix miscompilation with recent Apple Clang

src/lib/defect.hh, src/lib/parser-json-gcc.cc, src/lib/parser-json-sarif.cc, src/lib/parser-json-shchk.cc, src/lib/parser-json-simple.cc, src/lib/writer-json-sarif.cc, src/lib/writer-json-simple.cc, tests/csgrep/0078-json-parser-snyk-code-stdout.txt, tests/csgrep/0080-sarif-writer-stdout.txt, tests/csgrep/0082-sarif-parser-stdout.txt, tests/csgrep/0085-sarif-writer-stdout.txt, tests/csgrep/0090-sarif-writer-illegal-utf8-sequence-stdout.txt, tests/csgrep/0094-gcc-json-stdout.txt, tests/csgrep/0095-gcc-sarif-stdout.txt, tests/csgrep/0096-sarif-levels-stdout.txt, tests/csgrep/0097-sarif-set-tool-stdout.txt, tests/csgrep/0098-json-parser-shellcheck-stdout.txt, tests/csgrep/0100-sarif-parser-gitleaks-stdout.txt, tests/csgrep/0106-snyk-prepend-path-stdout.txt, tests/csgrep/0109-shellcheck-sarif-cwe-stdout.txt, tests/csgrep/0114-json-sc-column-stdout.txt, tests/csgrep/0120-sarif-parser-semgrep-stdout.txt
Initially csdiff supported only `startLine`/`startColumn`.  Some scanners provide also `endLine`/`endColumn` to denote a region of certain size.
The extra information is stored efficiently in the internal data structure and in csdiff's native JSON format by tracking the diff between `startLine`/`endLine` and `startColumn`/`endColumn`, respectively, and only when the diff is a non-zero (positive) number.
Resolves: https://github.com/csutils/csdiff/issues/136
=> propagate endLine/endColumn

src/lib/msg-filter.cc, tests/csdiff/CMakeLists.txt, tests/csdiff/diff-misc/21-kernel-shell-code-new.err, tests/csdiff/diff-misc/21-kernel-shell-code-old.err, tests/csdiff/diff-misc/22-kernel-zstream-path-new.err, tests/csdiff/diff-misc/22-kernel-zstream-path-old.err, tests/csdiff/diff-misc/sync.sh
... installed in `usr/src/kernels/...+debug/scripts`
Related: https://issues.redhat.com/browse/OSH-563
=> msg-filter: ignore version-release in kernel scripts and source files

src/cshtml.cc
Correctly reference accepted format as JSON instead of JS.
=> fix(cshtml): `.js` -> `.json`

src/lib/writer-html.cc, tests/cshtml/0001-smoke/scan-results.html, tests/cshtml/0002-cwe-names/scan-results.html
> [!NOTE]
>
> UTF-8 is the default encoding in HTML5
=> Use HTML5 instead of XHTML 1.0 :earth_africa: 

src/lib/writer-html.cc, tests/cshtml/0001-smoke/scan-results.html, tests/cshtml/0002-cwe-names/scan-results.html
The branch contains additional commits from:
- #179 
- #180 
Once they are accepted, I'll drop them.
This is just a DRAFT. There is probably a better way how to implement CSS into `writer-html`
=> use CSS instead of inlining styles :paintbrush: 

src/lib/msg-filter.cc, tests/csdiff/CMakeLists.txt, tests/csdiff/diff-misc/27-cov-builtin-model-new.err, tests/csdiff/diff-misc/27-cov-builtin-model-old.err
... so that semantically equal findings are matched with each other
Resolves: https://issues.redhat.com/browse/OSH-700
=> msg-filter: abstract out notes about builtin models

src/cstrans-df-run.cc
Related: https://github.com/csutils/csdiff/pull/190
=> cstrans-df-run: use std::move() suggested by Coverity

src/lib/writer-html.cc, tests/cshtml/0001-smoke/scan-results.html, tests/cshtml/0002-cwe-names/scan-results.html
... instead of "defect" in the reports.
Resolves: https://github.com/csutils/csdiff/issues/193
=> html-writer: use the term "finding"

make-srpm.sh, src/CMakeLists.txt
... with a statically linked csgrep-static executable needed for context embedding in legacy build environments.
=> introduce the csdiff-static subpackage

make-srpm.sh
The hard-coded `/usr/lib64` paths to Boost static libraries do not work well in 32bit buildroots and nobody is going to use the -static subpkg on a 32bit architecture anyway.
=> packaging: build the -static subpkg on 64bit arches only

src/lib/hash-util.hh
... where `TEng::digest_type` expands to an array of chars rather than an array of ints.  This caused each byte in the resulting hash string to be prepended by 3 zero bytes, which was detected by the CI on macOS:
```
--- /Users/runner/work/csdiff/csdiff/tests/csgrep/0036-csgrep-json-stdout.txt	2024-08-26 16:59:02
+++ -	2024-08-26 17:00:30
@@ -4,7 +4,7 @@
"checker": "SHELLCHECK_WARNING",
"language": "shell",
"tool": "shellcheck",
-            "hash_v1": "b6311c1fdc52c47d4279cd6650af36e6f8299960",
+            "hash_v1": "000000b6000000310000001c0000001f000000dc00000052000000c40000007d0000004200000079000000cd0000006600000050000000af00000036000000e6000000f8000000290000009900000060",
"key_event_idx": 0,
"events": [
{
```
Also use the `hex_lower` algorithm to optimize out the extra traversal …
=> hash-util: make the code work with boost-1.86

make-srpm.sh
The macro is not available in EPEL-7 buildroot and causes the build of csdiff to fail:
```
error: line 79: Unknown tag: %py_provides    python2-csdiff
```
This partially reverts commit df5c63fbbc676220c0c13e3d3e4070beeab0489f.
=> packaging: do not use `%py_provides` for Python 2

src/lib/parser-json-sarif.cc, tests/csgrep/0106-snyk-prepend-path-stdout.txt
... to 1 if `level` is `error`.  This is how `csgrep ---mode=sarif` encodes the `imp` flag.  As a side effect, all findings from Snyk Code with `level` set to `error` will be marked as important.  Nevertheless, this is what `csmock-plugin-snyk` explicitly does already: https://github.com/csutils/csmock/pull/122
Resolves: https://issues.redhat.com/browse/OSH-754
Closes: https://github.com/csutils/csdiff/pull/205
=> parser-json-sarif: initialize the `imp` flag

make-srpm.sh
If the buildroot contains outdated packages that do not yet contain definition of the macro, it causes the build of csdiff to fail with:
```
error: line 90: Unknown tag: %py_provides    python3-csdiff
```
This reverts commit df5c63fbbc676220c0c13e3d3e4070beeab0489f.
Fixes: commit f16db5adb1c0ccb2619c0e3d11badbc606796ae1
Closes: https://github.com/csutils/csdiff/pull/203
=> packaging: do not use `%py_provides` in epel-7 builds

src/csfilter-kfp, tests/csfilter-kfp/0002-stdout.txt, tests/csfilter-kfp/0003-stdout.txt
... in case `--kfp-git-url` is used without a pinned revision
Related: https://issues.redhat.com/browse/OSH-737
Closes: https://github.com/csutils/csdiff/pull/207
=> csfilter-kfp: record SHA1 hash of HEAD in JSON output

src/lib/csdiff-core.cc
This module does not use any specific writer.  It rather uses the generic `createWriter()` function, which is declared in `writer.hh`.
=> csdiff-core: include correct header file

.github/workflows/ubuntu.yml
... because these images are deprecated and will be unsupported by April.
Related: https://github.com/actions/runner-images/issues/11101
=> ci: remove Ubuntu 20.04 jobs

src/lib/msg-filter.cc, tests/csdiff/CMakeLists.txt, tests/csdiff/diff-misc/28-kernel-iv-dist-tag-add-z.err, tests/csdiff/diff-misc/28-kernel-iv-dist-tag-add.err, tests/csdiff/diff-misc/28-kernel-iv-dist-tag-fix-z.err, tests/csdiff/diff-misc/28-kernel-iv-dist-tag-fix.err, tests/csdiff/diff-misc/28-kernel-iv-dist-tag-new.err, tests/csdiff/diff-misc/28-kernel-iv-dist-tag-old.err
... that use the `el9_6iv` dist tag.  The regex we have been using did not accept the `iv` suffix.
Reported-by: Erico Nunes
=> msg-filter: tweak path substitution for RHIVOS kernels
